### PR TITLE
Add VoLTE support

### PR DESCRIPTION
**Pull request by KcNirvana**

### CODE REVIEW

**Comment by ale8530** [comment]
Sorry why this patch? o.o is not repo official

**Comment by KcNirvana** [comment]
Hello...
Just a fan of Miui Italia...
I saw that you are testing Face unlock feature.
If you want to provide VoLTE also, that is the way...

Sorry, if I offend you, I don't want to disrespect no one...

Best regards

**Comment by ale8530** [comment]
No problem thanks for your pr official repo-->https://github.com/MishFdM/Patch_MIUIV10 tomorrow update Same files here.

You have test this patch?

**Comment by KcNirvana** [comment]
Yes on a Vince.
This is working also on a Global rom if you change region to IN or HK
But to enable VoLTE (after the patch), you must dialer  *#*#86583#*#* to disable VoLTE check and enable the option in SIM Card Settings.
Your operator must support it and the APN of your operator have to support the IMS function:

screenshot_2018-08-20-23-17-15-667_com android settings

(I had to change APN Type and MVNO Type)

**Comment by ale8530** [comment]
Interesting solution, you have insert region "IT"? I don't see change mvno type

**Comment by KcNirvana** [comment]
Hello,
No. I've change the HK to IT, but I think if I add one more item the result will be the same.
Sorry, here's the SS completed:

screenshot_2018-08-21-08-46-48-739_com android settings

**Comment by ale8530** [comment]
KcNirvana is possible insert same PR here? https://github.com/MishFdM/Patch_MIUIV10 As soon as I fixed Mi Face Unlock I see LTE support :)

You have hangouts?

**Comment by KcNirvana** [comment]
Yes, I can.
And yes I have Hangouts.

**Comment by ale8530** [comment]
My contact Hangouts ale.8530@gmail.com

**Pull request closed without merging**
